// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function QRDataURL():Promise<string>;

export function ServerURL():Promise<string>;

export function StartCore():Promise<void>;

export function StopCore():Promise<void>;
