// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function QRDataURL() {
  return window['go']['main']['App']['QRDataURL']();
}

export function ServerURL() {
  return window['go']['main']['App']['ServerURL']();
}

export function StartCore() {
  return window['go']['main']['App']['StartCore']();
}

export function StopCore() {
  return window['go']['main']['App']['StopCore']();
}
